import { PrismaClient, Role, PlotSource } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const basePlots = [
  {
    id: "AC-101",
    slug: "ac-101-river-gate",
    title: "River Gate Commerce Zone",
    district: "North Gateway",
    purpose: "Commercial",
    area: 2.4,
    price: 420000,
    currency: "USD",
    roi: 18.2,
    irr: 21.1,
    riskScore: 28,
    legalGrade: "a_plus",
    status: "available",
    x: 22,
    y: 58,
    distanceCenterKm: 8.4,
    utilities: ["Electricity", "Water", "Gas"],
    tags: ["Top ROI", "Full verification"],
    ownerType: "Company",
    docs: ["Ownership certificate", "Cadastral plan", "No encumbrance certificate"],
    timeline: ["2026 Q2: Interchange upgrade", "2026 Q4: Main gas connection"],
  },
  {
    id: "AC-102",
    slug: "ac-102-tech-valley",
    title: "Tech Valley Mixed Use",
    district: "Innovation Belt",
    purpose: "Mixed-use",
    area: 1.8,
    price: 335000,
    currency: "USD",
    roi: 15.7,
    irr: 19.3,
    riskScore: 34,
    legalGrade: "a",
    status: "reserved",
    x: 41,
    y: 42,
    distanceCenterKm: 6.1,
    utilities: ["Electricity", "Water"],
    tags: ["Urgent sale"],
    ownerType: "Individual",
    docs: ["Ownership certificate", "Cadastral plan"],
    timeline: ["2026 Q3: Business incubator launch"],
  },
  {
    id: "AC-103",
    slug: "ac-103-logistics-yard",
    title: "Logistics Yard East",
    district: "Eastern Cargo Line",
    purpose: "Logistics",
    area: 4.2,
    price: 510000,
    currency: "USD",
    roi: 12.8,
    irr: 16,
    riskScore: 41,
    legalGrade: "b",
    status: "available",
    x: 68,
    y: 64,
    distanceCenterKm: 11.3,
    utilities: ["Electricity"],
    tags: ["Large lot"],
    ownerType: "Company",
    docs: ["Ownership certificate", "Cadastral plan"],
    timeline: ["2027 Q1: Rail node"],
  },
  {
    id: "AC-104",
    slug: "ac-104-residence-garden",
    title: "Residence Garden Block",
    district: "Green Spine",
    purpose: "Residential",
    area: 1.1,
    price: 198000,
    currency: "USD",
    roi: 13.6,
    irr: 17.2,
    riskScore: 30,
    legalGrade: "a",
    status: "deal",
    x: 34,
    y: 73,
    distanceCenterKm: 9.2,
    utilities: ["Electricity", "Water", "Gas"],
    tags: ["Family cluster"],
    ownerType: "Individual",
    docs: ["Ownership certificate", "Cadastral plan", "Technical conditions"],
    timeline: ["2026 Q4: School and kindergarten"],
  },
  {
    id: "AC-105",
    slug: "ac-105-lake-front",
    title: "Lake Front Hospitality",
    district: "Blue Crescent",
    purpose: "Hospitality",
    area: 3.6,
    price: 690000,
    currency: "USD",
    roi: 19.9,
    irr: 24.5,
    riskScore: 37,
    legalGrade: "a_plus",
    status: "available",
    x: 56,
    y: 27,
    distanceCenterKm: 5.8,
    utilities: ["Electricity", "Water", "Gas", "Fiber"],
    tags: ["Premium", "Growth leader"],
    ownerType: "Company",
    docs: ["Ownership certificate", "Cadastral plan", "No encumbrance certificate"],
    timeline: ["2026 Q2: Waterfront", "2027 Q2: Convention center"],
  },
  {
    id: "AC-106",
    slug: "ac-106-solar-hub",
    title: "Solar Hub Industrial Plot",
    district: "Energy Ring",
    purpose: "Industrial",
    area: 5.8,
    price: 740000,
    currency: "USD",
    roi: 11.3,
    irr: 14.4,
    riskScore: 44,
    legalGrade: "b",
    status: "moderation",
    x: 79,
    y: 34,
    distanceCenterKm: 13.8,
    utilities: ["Electricity", "Water"],
    tags: ["Energy cluster"],
    ownerType: "Company",
    docs: ["Ownership certificate"],
    timeline: ["2027 Q1: 220kV substation"],
  },
  {
    id: "AC-107",
    slug: "ac-107-medical-campus",
    title: "Medical Campus Plot",
    district: "Health Quarter",
    purpose: "Social infrastructure",
    area: 2.9,
    price: 390000,
    currency: "USD",
    roi: 14.9,
    irr: 18.8,
    riskScore: 31,
    legalGrade: "a",
    status: "available",
    x: 47,
    y: 55,
    distanceCenterKm: 7.3,
    utilities: ["Electricity", "Water", "Gas", "Fiber"],
    tags: ["Stable demand"],
    ownerType: "PPP",
    docs: ["Ownership certificate", "Cadastral plan", "Planning terms"],
    timeline: ["2026 Q3: Clinic phase 1"],
  },
  {
    id: "AC-108",
    slug: "ac-108-retail-corridor",
    title: "Retail Corridor Central",
    district: "Central Arc",
    purpose: "Retail",
    area: 1.3,
    price: 280000,
    currency: "USD",
    roi: 16.4,
    irr: 20.1,
    riskScore: 29,
    legalGrade: "a_plus",
    status: "sold",
    x: 25,
    y: 35,
    distanceCenterKm: 4.2,
    utilities: ["Electricity", "Water", "Gas"],
    tags: ["High traffic"],
    ownerType: "Company",
    docs: ["Ownership certificate", "Cadastral plan", "No encumbrance certificate"],
    timeline: ["2026 Q2: Mall phase 1"],
  },
  {
    id: "AC-109",
    slug: "ac-109-aviation-belt",
    title: "Aviation Belt Parcel",
    district: "Airport Link",
    purpose: "Logistics",
    area: 6.2,
    price: 880000,
    currency: "USD",
    roi: 17.1,
    irr: 22,
    riskScore: 53,
    legalGrade: "c",
    status: "legal_issue",
    x: 90,
    y: 49,
    distanceCenterKm: 18.4,
    utilities: ["Electricity"],
    tags: ["High potential"],
    ownerType: "Company",
    docs: ["Ownership certificate"],
    timeline: ["2027 Q3: Cargo terminal"],
  },
  {
    id: "AC-110",
    slug: "ac-110-education-park",
    title: "Education Park Campus",
    district: "Knowledge Loop",
    purpose: "Education",
    area: 2.2,
    price: 360000,
    currency: "USD",
    roi: 13.9,
    irr: 17.5,
    riskScore: 33,
    legalGrade: "a",
    status: "available",
    x: 61,
    y: 71,
    distanceCenterKm: 10.1,
    utilities: ["Electricity", "Water", "Gas", "Fiber"],
    tags: ["Long-term horizon"],
    ownerType: "PPP",
    docs: ["Ownership certificate", "Cadastral plan", "Technical conditions"],
    timeline: ["2026 Q4: University block"],
  },
] as const;

const baseBusinessProjects = [
  {
    id: "BIZ-101",
    status: "approved",
    moderationNote: "Published in small business projects section.",
    companyName: "GreenBox Local Foods",
    businessOverview:
      "Neighborhood mini-store chain with fast delivery for daily groceries in Alatau City districts.",
    market: "Urban grocery convenience retail in Alatau City",
    businessModel:
      "Margin on product sales plus subscription for same-day delivery and partner shelf placements.",
    traction:
      "Pilot point is operating 4 months. Average 210 orders/day, repeat rate 48%, positive unit economics.",
    legalReadiness: "LLP registered, lease agreements signed, tax and accounting setup complete.",
    financialForecasts:
      "Revenue target: 420k USD year 1 and 710k USD year 2, EBITDA margin goal 14% by month 18.",
    investmentTerms:
      "Seeking 120k USD for 15% equity, investor reporting monthly, board observer right included.",
    founderName: "Ayan Sadykov",
    founderEmail: "founder@greenbox.kz",
    founderPhone: "+7 700 555 1010",
    city: "Alatau City",
    website: "https://greenbox.example",
    requestedAmount: 120000,
    minimumTicket: 15000,
  },
  {
    id: "BIZ-102",
    status: "under_review",
    moderationNote: null,
    companyName: "QuickFix Home Service",
    businessOverview:
      "Mobile platform for urgent home repair micro-services: electrician, plumbing, appliance fixes.",
    market: "On-demand home repair services for apartments and small offices",
    businessModel:
      "Commission from each order plus contractor subscription for premium lead priority.",
    traction:
      "MVP app launched, 320 completed jobs, NPS 69, 140 active paying customers.",
    legalReadiness: "Sole proprietorship active, service contracts template approved by legal advisor.",
    financialForecasts:
      "Projected GMV 260k USD in 12 months; break-even expected in month 10 at 1,100 orders/month.",
    investmentTerms:
      "Raising 60k USD via SAFE note with 2.8M USD valuation cap and 20% discount at next round.",
    founderName: "Timur Nurpeisov",
    founderEmail: "timur@quickfix.kz",
    founderPhone: "+7 701 111 2233",
    city: "Alatau City",
    website: null,
    requestedAmount: 60000,
    minimumTicket: 5000,
  },
] as const;

async function main() {
  const adminPassword = await bcrypt.hash("Admin#2026", 10);
  const investorPassword = await bcrypt.hash("Investor#2026", 10);
  const ownerPassword = await bcrypt.hash("Owner#2026", 10);

  const admin = await prisma.user.upsert({
    where: { email: "admin@alatau.city" },
    update: { role: Role.ADMIN, passwordHash: adminPassword, name: "Platform Admin" },
    create: {
      email: "admin@alatau.city",
      name: "Platform Admin",
      role: Role.ADMIN,
      passwordHash: adminPassword,
    },
  });

  await prisma.user.upsert({
    where: { email: "investor@alatau.city" },
    update: { role: Role.INVESTOR, passwordHash: investorPassword, name: "Demo Investor" },
    create: {
      email: "investor@alatau.city",
      name: "Demo Investor",
      role: Role.INVESTOR,
      passwordHash: investorPassword,
    },
  });

  const owner = await prisma.user.upsert({
    where: { email: "owner@alatau.city" },
    update: { role: Role.OWNER, passwordHash: ownerPassword, name: "Demo Owner" },
    create: {
      email: "owner@alatau.city",
      name: "Demo Owner",
      role: Role.OWNER,
      passwordHash: ownerPassword,
    },
  });

  for (const plot of basePlots) {
    await prisma.plot.upsert({
      where: { id: plot.id },
      update: {
        ...plot,
        source: PlotSource.platform,
      },
      create: {
        ...plot,
        source: PlotSource.platform,
        ownerId: plot.id === "AC-106" ? owner.id : admin.id,
      },
    });
  }

  for (const project of baseBusinessProjects) {
    await prisma.businessProject.upsert({
      where: { id: project.id },
      update: {
        status: project.status,
        moderationNote: project.moderationNote,
        companyName: project.companyName,
        businessOverview: project.businessOverview,
        market: project.market,
        businessModel: project.businessModel,
        traction: project.traction,
        legalReadiness: project.legalReadiness,
        financialForecasts: project.financialForecasts,
        investmentTerms: project.investmentTerms,
        founderName: project.founderName,
        founderEmail: project.founderEmail,
        founderPhone: project.founderPhone,
        city: project.city,
        website: project.website,
        requestedAmount: project.requestedAmount,
        minimumTicket: project.minimumTicket,
        userId: project.id === "BIZ-101" ? owner.id : admin.id,
      },
      create: {
        id: project.id,
        status: project.status,
        moderationNote: project.moderationNote,
        companyName: project.companyName,
        businessOverview: project.businessOverview,
        market: project.market,
        businessModel: project.businessModel,
        traction: project.traction,
        legalReadiness: project.legalReadiness,
        financialForecasts: project.financialForecasts,
        investmentTerms: project.investmentTerms,
        founderName: project.founderName,
        founderEmail: project.founderEmail,
        founderPhone: project.founderPhone,
        city: project.city,
        website: project.website,
        requestedAmount: project.requestedAmount,
        minimumTicket: project.minimumTicket,
        userId: project.id === "BIZ-101" ? owner.id : admin.id,
      },
    });
  }

  console.log("Seed complete.");
  console.log("Admin login: admin@alatau.city / Admin#2026");
  console.log("Investor login: investor@alatau.city / Investor#2026");
  console.log("Owner login: owner@alatau.city / Owner#2026");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
